// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjfw1_0eiMT_3mEdkrLxS-_O9gIc7PEzo',
    appId: '1:196887051542:web:03f8209815c39accfa6437',
    messagingSenderId: '196887051542',
    projectId: 'clean-and-green-621e2',
    authDomain: 'clean-and-green-621e2.firebaseapp.com',
    storageBucket: 'clean-and-green-621e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKWLMIP3hSS6NjvIpMTaQrS9PiPK33EiI',
    appId: '1:196887051542:android:1d37f2051b7b9e32fa6437',
    messagingSenderId: '196887051542',
    projectId: 'clean-and-green-621e2',
    storageBucket: 'clean-and-green-621e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8FzBPa6lW5CZC5oe-2fPPpqneeNzIsr8',
    appId: '1:196887051542:ios:ed72f18c25a80430fa6437',
    messagingSenderId: '196887051542',
    projectId: 'clean-and-green-621e2',
    storageBucket: 'clean-and-green-621e2.appspot.com',
    iosBundleId: 'com.example.cleanGreenAdminAndWorker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8FzBPa6lW5CZC5oe-2fPPpqneeNzIsr8',
    appId: '1:196887051542:ios:ed72f18c25a80430fa6437',
    messagingSenderId: '196887051542',
    projectId: 'clean-and-green-621e2',
    storageBucket: 'clean-and-green-621e2.appspot.com',
    iosBundleId: 'com.example.cleanGreenAdminAndWorker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjfw1_0eiMT_3mEdkrLxS-_O9gIc7PEzo',
    appId: '1:196887051542:web:8355a3012de3f20efa6437',
    messagingSenderId: '196887051542',
    projectId: 'clean-and-green-621e2',
    authDomain: 'clean-and-green-621e2.firebaseapp.com',
    storageBucket: 'clean-and-green-621e2.appspot.com',
  );
}
